# Generated by Django 5.2.7 on 2025-11-06 01:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('thumb', models.ImageField(upload_to='thumb_filmes')),
                ('descricao', models.TextField(max_length=500)),
                ('categoria', models.CharField(choices=[('WORLDS', 'WORLDS'), ('KDA', 'KDA'), ('TRUE DAMAGE', 'True Damage'), ('PENTAKILL', 'Pentakill'), ('HEARTSTEEL', 'Heartsteel')], max_length=100)),
                ('data_criacao', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('video', models.URLField()),
                ('thumb', models.ImageField(upload_to='thumb_filmes')),
                ('descricao', models.TextField(max_length=500)),
                ('data_criacao', models.DateField(default=django.utils.timezone.now)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musica_filme', to='filme.filme')),
            ],
        ),
    ]
